$(`<center><div><marquee direction="right" width="99%" id="AL-HADED55" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="5">قوانين الشات ● • في حال ذكر وتبيين اسماء مواقع اخرى تعرضك لحذف العضوية والحظر يرجى من الزوار والمراقبين عدم ذكر اسماء مواقع اخرى ● • وشكرآ لكم</marquee></font><center>
`).insertBefore('label.nosel.ninr.fl.uzr.label.label-primary');

 $(`<a  style="margin-top:-20px;padding :4px;float:right;border-radius:100px;" class="btn d btn-danger fa fa-spin fa-heart fr"></a></div>`).insertBefore('div#d2bc')

$(`<img src ="sico/z1emv9lhk810.jpg" etclass="fr" style="width:100%;margin-top: 1px;">
</div>
<div id="Hos"><center><a id="AL-HADED9" href="" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">التطبيق</a><a id="Hos" href="" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">اشتراكات</a>
<a id="tof3" href="" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">القوانين</a><div style=" width: 22%; "  id="AL-HADED" class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">اتصل بنا</div><div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary">  </p>راسلنا تليكرام اذا كنت محظور </p> 
   <i class="fa fa-comment"></i>  Facebook <i class="fa fa-share"></i>ommmar.axx2015</p>  <i class="fa fa-comment"></i> Telegram <i class="fa fa-share"></i> @ihtc0 </p>  <i class="fa fa fa-comment"></i> WATSAPP <i class="fa fa-share"></i> +962798954023 </div></div><center></div></div><center></div>`).insertBefore('.nav-tabs')

$('.checkbox label').html(`<input id="stealth" type="checkbox" value=""><img style="width: 22px;" src="sico/z1en05jguh10.gif" width="100%">`)

$('.nav-tabs').addClass('fl').css('width','100%')

$(`
<link rel="stylesheet" href="https://rawcdn.githack.com/omar-alhaded/555/db3ec6909306217f921bae0ffb321beab56732b3/Alhaded.css">
<style>
textarea.fl.filw.corner.tbox {border-radius: 10px;padding-left: 5px;border: 2px solid #adadad;margin-top: 2px;}
.label.tc.border.btn.fl, .label.tc.border.btn.fl {border: 2px solid #adadad;font-family: 'jazeera',FontAwesome;border-radius: 24px 24px 24px 24px;}
</style>`).insertBefore('body'); 	
function pmsg(){var m=prompt('الرجاء الالتزام بقواعد الاعلانات الاعلانات فقط للمسابقات والادعية ليسة للمزح صاحب الشات عمر الحديد',"");if(m==''||m==null){return;}
m=m.split('\n').join('');if(m=="%0A"||m=="%0a"||m==''||m=='\n'){return;}
send("pmsg",{msg:m});}
$(".fa-gear").text("الضـبط").css("width","");
$("div#tlogins input").attr("maxlength",10),$("textarea#tbox.fl.corner.tbox.filw").attr("maxlength",1000);

$(".ubnr").remove(); 
$(".fr.co").hide();
$(".fl.mini.u-co").hide();
$(`<center><div><div width="99.5%" id="" /font/div/div><center>`).insertBefore('#d2');
bct=100;msgt=100;
